### ISSUE TITLE
Need to compile Sass?

### ISSUE THREAD

**Issue by ISOC-NO** [InternetSocietyChapters/isoc2017-wp#1]
I activated the plugins mentioned, and changed theme. Result was not... pretty :) 
(Current theme; Internet Society WordPress ThemeVersion: v1.0.12 By Internet Society) - www.isoc.no
Know how to fix this?

![image](https://cloud.githubusercontent.com/assets/26328775/23802048/63749cea-05b2-11e7-9e7f-088c55259206.png)

**Comment by InternetSocietyChapters** [comment]
Thanks for reporting the issue! We've uploaded the dist-folder to GitHub now al well so you don't need Sass. We found another issue with the H2 font on Windows cluttering - we'll fix that next week.
