### ISSUE TITLE
There is no Theme Download Zip

### ISSUE THREAD

**Issue by ghost** [InternetSocietyChapters/isoc2017-wp#3]
> https://github.com/InternetSocietyChapters/isoc2017-wp/releases
> 
> IMPORTANT - In order for some of the sample code to work in this documentation, you should click on **"Theme download (zip)"** in order to download a version of the theme that unzips into a folder called simply "isoc". If you choose the other buttons marked "Source code" it will unzip into a folder called "isoc-version". This will work with WordPress, but some of the examples here will need to be modified. It's easier if you just have the folder/directory named "isoc".

Your README has this info, but there is only the clone/download (master) or if you go to releases, you can only find the Source Code (0.1) Zip files.

**Comment by oebe** [comment]
Issued a Release!

**Comment by boamaod** [comment]
Still can't find it. Opening https://github.com/InternetSocietyChapters/isoc2017-wp/releases and searching for "Theme download" gives only link to this issue in a bug tracker. Renamed the directory in ZIP as workaround, hope it will be enough.
